AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.0
  DisplayCopNames: true

Documentation:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Layout/DotPosition:
  EnforcedStyle: leading

Layout/IndentArray:
  EnforcedStyle: special_inside_parentheses

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: true

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
    
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RedundantBegin:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    reduce: 'inject'

Style/ClassCheck:
  EnforcedStyle: kind_of?

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
   
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
