AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  Rails:
    Enabled: true

Documentation:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/migrate/**/*'


Style/IndentArray:
  EnforcedStyle: special_inside_parentheses

Style/LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RedundantBegin:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: true

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    reduce: 'inject'

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/DotPosition:
  EnforcedStyle: leading

Style/SpaceBeforeBlockBraces:
  Enabled: false
