version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3111 -b '0.0.0.0'
    volumes:
      - .:/league_api
    ports:
      - "3111:3111"
    depends_on:
      - db
