development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  username: <%= ENV['DB_USER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: league_api_test

staging:
  <<: *default

production:
  <<: *default
