development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: league_development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: league_test

staging:
  <<: *default

production:
  <<: *default
