development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: league_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: league_test

staging:
  <<: *default

production:
  <<: *default
