development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME_TEST'] %>

staging:
  <<: *default

production:
  <<: *default
